"""Local, demo-safe persistence for MiroFish v2 runs."""

from __future__ import annotations

import json
import os
import re
import shutil
import threading
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any, Dict
from uuid import uuid4

try:  # Unix file locking; the process lock below remains available elsewhere.
    import fcntl
except ImportError:  # pragma: no cover - exercised only on Windows
    fcntl = None

from ..config import Config
from .schemas import V2RunState


class V2Storage:
    RUNS_DIR = Path(Config.UPLOAD_FOLDER) / "v2_runs"
    RUN_ID_PATTERN = re.compile(r"^v2_\d{14}_[0-9a-f]{8}$")
    PENDING_REVISION_FILENAME = ".pending_revision.json"
    DERIVED_JSON_ARTIFACTS = (
        "graph.json",
        "assumptions.json",
        "contradictions.json",
        "hypotheses.json",
        "internal_questions.json",
        "internal_evidence.json",
        "decision_impacts.json",
        "stop_evaluation.json",
        "audit_trail.json",
        "token_usage.json",
    )
    _LOCKS_GUARD = threading.Lock()
    _PROCESS_LOCKS: Dict[str, threading.RLock] = {}
    _LOCK_DEPTHS = threading.local()

    @classmethod
    def ensure_root(cls) -> None:
        cls._ensure_private_dir(cls.RUNS_DIR)

    @classmethod
    def create_run_id(cls) -> str:
        stamp = datetime.now().strftime("%Y%m%d%H%M%S")
        return f"v2_{stamp}_{uuid4().hex[:8]}"

    @classmethod
    def run_dir(cls, run_id: str) -> Path:
        if not isinstance(run_id, str) or not cls.RUN_ID_PATTERN.fullmatch(run_id):
            raise FileNotFoundError(f"v2 run not found: {run_id}")
        cls.ensure_root()
        return cls.RUNS_DIR / run_id

    @classmethod
    def pack_dir(cls, run_id: str) -> Path:
        path = cls.run_dir(run_id) / "research_pack"
        cls._ensure_private_dir(path)
        return path

    @classmethod
    def state_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / "state.json"

    @classmethod
    def report_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / "decision_memo.md"

    @classmethod
    def discard_uninitialized_run(cls, run_id: str) -> bool:
        """Remove a provisional upload directory when import never produced state.

        Run IDs are generated by this service and validated by ``run_dir``.  The
        state-file guard deliberately preserves any run that reached durable
        initialization, even if a later report/artifact write failed.
        """
        run_dir = cls.run_dir(run_id)
        if not run_dir.exists() or cls.state_path(run_id).exists():
            return False
        shutil.rmtree(run_dir)
        return True

    @classmethod
    def artifact_path(cls, run_id: str, filename: str) -> Path:
        return cls.run_dir(run_id) / filename

    @classmethod
    def save_state(cls, state: V2RunState) -> None:
        """Durably publish a state revision with ``state.json`` as commit point.

        Derived files and the audit JSONL are prepared first.  A private marker
        records how to restore the previously committed revision if any of those
        writes (or the final state replacement) fails.  Once ``state.json`` is
        replaced, every required write is already complete; marker cleanup is
        deliberately best-effort and can be finalized by the next load.
        """
        with cls.lock_run(state.run_id):
            cls._recover_pending_revision(state.run_id)
            cls._save_state_locked(state)

    @classmethod
    def _save_state_locked(cls, state: V2RunState) -> None:
        run_dir = cls.run_dir(state.run_id)
        cls._ensure_private_dir(run_dir)
        cls._harden_run_permissions(state.run_id)

        canonical_payload = cls._read_state_payload(state.run_id)
        canonical_revision = (
            int(canonical_payload.get("state_revision", 0)) if canonical_payload is not None else None
        )
        canonical_audit = canonical_payload.get("audit_trail", []) if canonical_payload else []
        audit_prefix_size = cls._canonical_audit_prefix_size(state.run_id, canonical_audit)

        original_revision = state.state_revision
        original_updated_at = state.updated_at
        graph_had_state_revision = "state_revision" in state.graph
        original_graph_state_revision = state.graph.get("state_revision")

        state.touch()
        state.state_revision = original_revision + 1
        if state.graph:
            state.graph["state_revision"] = state.state_revision
        target_revision = state.state_revision
        payload: Dict[str, Any] = state.model_dump(mode="json")
        pending_payload = {
            "target_revision": target_revision,
            "canonical_revision": canonical_revision,
            "audit_jsonl_prefix_size": audit_prefix_size,
        }

        try:
            cls._atomic_write_json(cls._pending_revision_path(state.run_id), pending_payload)
            cls._write_derived_artifacts(state)

            graph_history_dir = run_dir / "graph_revisions"
            cls._ensure_private_dir(graph_history_dir)
            graph_revision_path = graph_history_dir / f"revision_{target_revision:03d}.json"
            # A failed attempt may have left this target revision behind.  It is
            # uncommitted while canonical state is older, so always replace it.
            cls._atomic_write_json(graph_revision_path, state.graph)

            # Final and only commit point.  Nothing required may be written after
            # this replacement succeeds.
            cls._atomic_write_json(cls.state_path(state.run_id), payload)
        except Exception:
            # If an injected error happened after os.replace, the canonical file
            # still proves that the transaction committed.  Otherwise restore the
            # caller's in-memory revision so a retry does not skip a number.
            committed = cls._state_revision_on_disk(state.run_id) == target_revision
            if not committed:
                state.state_revision = original_revision
                state.updated_at = original_updated_at
                if graph_had_state_revision:
                    state.graph["state_revision"] = original_graph_state_revision
                else:
                    state.graph.pop("state_revision", None)
                raise

        cls._remove_pending_marker_best_effort(state.run_id)

    @classmethod
    def _write_derived_artifacts(cls, state: V2RunState) -> None:
        cls._write_artifact(state.run_id, "graph.json", state.graph)
        cls._write_artifact(
            state.run_id,
            "assumptions.json",
            [item.model_dump(mode="json") for item in state.assumptions],
        )
        cls._write_artifact(
            state.run_id,
            "contradictions.json",
            [item.model_dump(mode="json") for item in state.contradictions],
        )
        cls._write_artifact(
            state.run_id,
            "hypotheses.json",
            [item.model_dump(mode="json") for item in state.hypotheses],
        )
        cls._write_artifact(
            state.run_id,
            "internal_questions.json",
            [item.model_dump(mode="json") for item in state.internal_questions],
        )
        cls._write_artifact(
            state.run_id,
            "internal_evidence.json",
            [item.model_dump(mode="json") for item in state.internal_evidence],
        )
        cls._write_artifact(
            state.run_id,
            "decision_impacts.json",
            [item.model_dump(mode="json") for item in state.decision_impacts],
        )
        cls._write_artifact(
            state.run_id,
            "stop_evaluation.json",
            state.stop_evaluation.model_dump(mode="json") if state.stop_evaluation else {},
        )
        audit_rows = [item.model_dump(mode="json") for item in state.audit_trail]
        cls._write_artifact(state.run_id, "audit_trail.json", audit_rows)
        cls._append_jsonl(state.run_id, "audit_trail.jsonl", audit_rows)
        cls._write_artifact(
            state.run_id,
            "token_usage.json",
            state.token_usage.model_dump(mode="json"),
        )
        if state.report:
            cls._atomic_write_text(cls.report_path(state.run_id), state.report.markdown)
        else:
            cls._remove_file_if_present(cls.report_path(state.run_id))

    @classmethod
    @contextmanager
    def lock_run(cls, run_id: str, *, require_existing: bool = False):
        """Serialize local read-modify-write transactions for one decision case."""
        run_dir = cls.run_dir(run_id)
        if require_existing and not cls.state_path(run_id).is_file():
            raise FileNotFoundError(f"v2 run not found: {run_id}")
        cls._ensure_private_dir(run_dir)
        lock_path = run_dir / ".state.lock"
        lock_key = str(lock_path)
        with cls._LOCKS_GUARD:
            process_lock = cls._PROCESS_LOCKS.setdefault(lock_key, threading.RLock())
        with process_lock:
            depths = getattr(cls._LOCK_DEPTHS, "values", None)
            if depths is None:
                depths = {}
                cls._LOCK_DEPTHS.values = depths
            if depths.get(lock_key, 0):
                depths[lock_key] += 1
                try:
                    yield
                finally:
                    depths[lock_key] -= 1
                return

            lock_fd = os.open(lock_path, os.O_RDWR | os.O_APPEND | os.O_CREAT, 0o600)
            with os.fdopen(lock_fd, "a+", encoding="utf-8") as lock_file:
                if fcntl is not None:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
                depths[lock_key] = 1
                try:
                    yield
                finally:
                    depths.pop(lock_key, None)
                    if fcntl is not None:
                        fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)

    @classmethod
    def load_state(cls, run_id: str) -> V2RunState:
        path = cls.state_path(run_id)
        if not path.exists():
            raise FileNotFoundError(f"v2 run not found: {run_id}")
        with cls.lock_run(run_id):
            # Recheck after waiting for a writer: a provisional/failed initial
            # transaction may have been cleaned up while this reader blocked.
            if not path.exists():
                raise FileNotFoundError(f"v2 run not found: {run_id}")
            cls._recover_pending_revision(run_id)
            cls._harden_run_permissions(run_id)
            payload = cls._read_state_payload(run_id)
            if payload is None:  # pragma: no cover - guarded by the checks above
                raise FileNotFoundError(f"v2 run not found: {run_id}")
            return V2RunState.model_validate(payload)

    @classmethod
    def _recover_pending_revision(cls, run_id: str) -> None:
        marker_path = cls._pending_revision_path(run_id)
        if not marker_path.exists():
            return

        with marker_path.open("r", encoding="utf-8") as marker_file:
            marker = json.load(marker_file)
        target_revision = int(marker["target_revision"])
        canonical_payload = cls._read_state_payload(run_id)
        canonical_revision = (
            int(canonical_payload.get("state_revision", 0)) if canonical_payload is not None else None
        )

        if canonical_revision == target_revision:
            # All derived writes preceded the state commit, so this is only a
            # marker-cleanup retry.  Cleanup remains optional for readability.
            cls._remove_pending_marker_best_effort(run_id)
            return

        # The target never committed.  Rebuild every public derivative from the
        # canonical old state before exposing it, and remove snapshots newer than
        # that state so a retry cannot inherit a poisoned graph revision.
        audit_prefix_size = int(marker.get("audit_jsonl_prefix_size", 0))
        if canonical_payload is None:
            cls._remove_uncommitted_derivatives(run_id)
        else:
            cls._restore_canonical_derivatives(run_id, canonical_payload, audit_prefix_size)
        cls._remove_graph_snapshots_after(run_id, canonical_revision or 0)
        marker_path.unlink()

    @classmethod
    def _restore_canonical_derivatives(
        cls,
        run_id: str,
        payload: Dict[str, Any],
        audit_prefix_size: int,
    ) -> None:
        state = V2RunState.model_validate(payload)
        audit_path = cls.artifact_path(run_id, "audit_trail.jsonl")
        cls._truncate_file(audit_path, audit_prefix_size)

        # JSONL must represent the canonical audit list, but its already-committed
        # prefix is retained byte-for-byte and only missing canonical rows append.
        cls._write_derived_artifacts(state)

    @classmethod
    def _remove_uncommitted_derivatives(cls, run_id: str) -> None:
        for filename in (*cls.DERIVED_JSON_ARTIFACTS, "audit_trail.jsonl"):
            cls._remove_file_if_present(cls.artifact_path(run_id, filename))
        cls._remove_file_if_present(cls.report_path(run_id))

    @classmethod
    def _remove_graph_snapshots_after(cls, run_id: str, canonical_revision: int) -> None:
        graph_history_dir = cls.run_dir(run_id) / "graph_revisions"
        if not graph_history_dir.exists():
            return
        for path in graph_history_dir.glob("revision_*.json"):
            try:
                revision = int(path.stem.rsplit("_", 1)[1])
            except (IndexError, ValueError):
                continue
            if revision > canonical_revision:
                path.unlink()

    @classmethod
    def _canonical_audit_prefix_size(cls, run_id: str, rows: Any) -> int:
        path = cls.artifact_path(run_id, "audit_trail.jsonl")
        if not path.exists() or not rows:
            return 0
        expected_ids = [row.get("event_id") for row in rows]
        raw = path.read_bytes()
        valid_end = 0
        matched = 0
        for line in raw.splitlines(keepends=True):
            if matched >= len(expected_ids):
                break
            candidate = line.rstrip(b"\r\n")
            try:
                decoded = json.loads(candidate.decode("utf-8"))
                event_id = decoded.get("event_id")
            except (UnicodeDecodeError, json.JSONDecodeError, AttributeError):
                break
            if event_id != expected_ids[matched]:
                break
            valid_end += len(line)
            matched += 1
        return valid_end

    @classmethod
    def _pending_revision_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / cls.PENDING_REVISION_FILENAME

    @classmethod
    def _read_state_payload(cls, run_id: str) -> Dict[str, Any] | None:
        path = cls.state_path(run_id)
        if not path.exists():
            return None
        with path.open("r", encoding="utf-8") as state_file:
            return json.load(state_file)

    @classmethod
    def _state_revision_on_disk(cls, run_id: str) -> int | None:
        try:
            payload = cls._read_state_payload(run_id)
            return int(payload.get("state_revision", 0)) if payload is not None else None
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            return None

    @classmethod
    def _remove_pending_marker_best_effort(cls, run_id: str) -> None:
        try:
            cls._pending_revision_path(run_id).unlink(missing_ok=True)
        except OSError:
            # The state commit is authoritative; a later load recognizes the
            # committed target and retries this optional cleanup.
            pass

    @classmethod
    def _remove_file_if_present(cls, path: Path) -> None:
        path.unlink(missing_ok=True)

    @classmethod
    def _truncate_file(cls, path: Path, size: int) -> None:
        if not path.exists():
            return
        with path.open("r+b") as output:
            output.truncate(size)
            output.flush()
            os.fsync(output.fileno())
        cls._harden_file(path)

    @classmethod
    def safe_filename(cls, filename: str) -> str:
        base = os.path.basename(filename or "document.txt")
        safe = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in base)
        return safe or "document.txt"

    @classmethod
    def _write_artifact(cls, run_id: str, filename: str, payload: Any) -> None:
        cls._atomic_write_json(cls.artifact_path(run_id, filename), payload)

    @classmethod
    def _append_jsonl(cls, run_id: str, filename: str, rows: Any) -> None:
        path = cls.artifact_path(run_id, filename)
        existing_ids = set()
        needs_separator = False
        if path.exists():
            raw = path.read_bytes()
            valid_end = 0
            for line in raw.splitlines(keepends=True):
                candidate = line.rstrip(b"\r\n")
                try:
                    payload = json.loads(candidate.decode("utf-8"))
                    event_id = payload.get("event_id")
                except (UnicodeDecodeError, json.JSONDecodeError, AttributeError):
                    break
                valid_end += len(line)
                if event_id:
                    existing_ids.add(event_id)
            if valid_end < len(raw):
                with path.open("r+b") as existing:
                    existing.truncate(valid_end)
                    existing.flush()
                    os.fsync(existing.fileno())
                raw = raw[:valid_end]
            needs_separator = bool(raw and not raw.endswith((b"\n", b"\r")))
        missing = [row for row in rows if row.get("event_id") not in existing_ids]
        if not missing:
            return
        output_fd = os.open(path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o600)
        with os.fdopen(output_fd, "a", encoding="utf-8") as output:
            if needs_separator:
                output.write("\n")
            for row in missing:
                output.write(json.dumps(row, ensure_ascii=False) + "\n")
            output.flush()
            os.fsync(output.fileno())

    @classmethod
    def _atomic_write_json(cls, path: Path, payload: Any) -> None:
        cls._atomic_write_text(path, json.dumps(payload, ensure_ascii=False, indent=2))

    @classmethod
    def _atomic_write_text(cls, path: Path, text: str) -> None:
        cls._ensure_private_dir(path.parent)
        temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
        try:
            temporary_fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(temporary_fd, "w", encoding="utf-8") as output:
                output.write(text)
                output.flush()
                os.fsync(output.fileno())
            os.replace(temporary, path)
            cls._harden_file(path)
        except Exception:
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass
            raise

    @staticmethod
    def _harden_file(path: Path) -> None:
        try:
            path.chmod(0o600)
        except OSError:  # pragma: no cover - permission modes vary on Windows
            pass

    @classmethod
    def _ensure_private_dir(cls, path: Path) -> None:
        path.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            path.chmod(0o700)
        except OSError:  # pragma: no cover - permission modes vary on Windows
            pass

    @classmethod
    def _harden_run_permissions(cls, run_id: str) -> None:
        """Migrate an existing case to owner-only filesystem permissions."""
        run_dir = cls.run_dir(run_id)
        if not run_dir.exists():
            return
        cls._ensure_private_dir(run_dir)
        for child in run_dir.rglob("*"):
            if child.is_symlink():
                continue
            if child.is_dir():
                cls._ensure_private_dir(child)
            elif child.is_file():
                cls._harden_file(child)
