"""Local, demo-safe persistence for MiroFish v2 runs."""

from __future__ import annotations

import json
import os
import re
import shutil
import threading
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List
from uuid import uuid4

try:  # Unix file locking; the process lock below remains available elsewhere.
    import fcntl
except ImportError:  # pragma: no cover - exercised only on Windows
    fcntl = None

from ..config import Config
from ..utils.safe_path import UnsafePathError, safe_child_path, safe_filename_path
from .schemas import V2RunState


class ImmutableRunError(RuntimeError):
    """Raised when code attempts to overwrite a sealed public baseline."""


class ConfidentialStorageUnavailable(RuntimeError):
    """Raised when a deployment has no approved confidential storage mode."""


class ConfidentialEvidenceError(RuntimeError):
    """Raised when a confidential evidence reference cannot be verified."""


class V2Storage:
    RUNS_DIR = Path(Config.UPLOAD_FOLDER) / "v2_runs"
    RUN_ID_PATTERN = re.compile(r"^v2_\d{14}_[0-9a-f]{8}$")
    PENDING_REVISION_FILENAME = ".pending_revision.json"
    CONFIDENTIAL_ANSWER_MARKER = "[CONFIDENTIAL_ANSWER_STORED_SEPARATELY]"
    DERIVED_JSON_ARTIFACTS = (
        "graph.json",
        "assumptions.json",
        "contradictions.json",
        "hypotheses.json",
        "internal_questions.json",
        "internal_evidence.json",
        "decision_impacts.json",
        "execution_plan.json",
        "stop_evaluation.json",
        "audit_trail.json",
        "token_usage.json",
        "core_lineage.json",
        "research_job.json",
        "targeted_reevaluations.json",
        "decision_model_proposal.json",
        "decision_model.json",
        "decision_analysis_result.json",
        "decision_analysis_options.json",
        "decision_analysis_audit.json",
        "evidence_update_proposals.json",
    )
    _LOCKS_GUARD = threading.Lock()
    _PROCESS_LOCKS: Dict[str, threading.RLock] = {}
    _LOCK_DEPTHS = threading.local()

    @classmethod
    def ensure_root(cls) -> None:
        cls._ensure_private_dir(cls.RUNS_DIR)

    @classmethod
    def create_run_id(cls) -> str:
        stamp = datetime.now().strftime("%Y%m%d%H%M%S")
        return f"v2_{stamp}_{uuid4().hex[:8]}"

    @classmethod
    def list_run_ids(cls) -> List[str]:
        cls.ensure_root()
        return sorted(
            path.name
            for path in cls.RUNS_DIR.iterdir()
            if path.is_dir()
            and cls.RUN_ID_PATTERN.fullmatch(path.name)
            and (path / "state.json").is_file()
        )

    @classmethod
    def run_dir(cls, run_id: str) -> Path:
        cls.ensure_root()
        try:
            return safe_child_path(
                cls.RUNS_DIR,
                run_id,
                label="run ID",
                pattern=cls.RUN_ID_PATTERN,
            )
        except UnsafePathError:
            # Invalid and absent IDs are intentionally indistinguishable to
            # public callers, and no supplied value or host path is echoed.
            raise FileNotFoundError("v2 run not found") from None

    @classmethod
    def pack_dir(cls, run_id: str) -> Path:
        path = cls.run_dir(run_id) / "research_pack"
        cls._ensure_private_dir(path)
        return path

    @classmethod
    def state_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / "state.json"

    @classmethod
    def report_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / "decision_memo.md"

    @classmethod
    def calculation_trace_path(cls, run_id: str, trace_id: str) -> Path:
        root = cls.run_dir(run_id) / "calculation_traces"
        cls._ensure_private_dir(root)
        try:
            return safe_filename_path(root, f"{trace_id}.json", label="trace ID")
        except UnsafePathError:
            raise FileNotFoundError("calculation trace not found") from None

    @classmethod
    def load_calculation_trace(cls, run_id: str, trace_id: str) -> Dict[str, Any]:
        path = cls.calculation_trace_path(run_id, trace_id)
        if not path.is_file():
            raise FileNotFoundError("calculation trace not found")
        with path.open("r", encoding="utf-8") as source:
            payload = json.load(source)
        if not isinstance(payload, dict):
            raise ValueError("calculation trace is invalid")
        return payload

    @classmethod
    def discard_uninitialized_run(cls, run_id: str) -> bool:
        """Remove a provisional upload directory when import never produced state.

        Run IDs are generated by this service and validated by ``run_dir``.  The
        state-file guard deliberately preserves any run that reached durable
        initialization, even if a later report/artifact write failed.
        """
        run_dir = cls.run_dir(run_id)
        if not run_dir.exists() or cls.state_path(run_id).exists():
            return False
        shutil.rmtree(run_dir)
        return True

    @classmethod
    def artifact_path(cls, run_id: str, filename: str) -> Path:
        try:
            return safe_filename_path(cls.run_dir(run_id), filename, label="artifact name")
        except UnsafePathError:
            raise FileNotFoundError("v2 artifact not found") from None

    @classmethod
    def save_state(cls, state: V2RunState) -> None:
        """Durably publish a state revision with ``state.json`` as commit point.

        Derived files and the audit JSONL are prepared first.  A private marker
        records how to restore the previously committed revision if any of those
        writes (or the final state replacement) fails.  Once ``state.json`` is
        replaced, every required write is already complete; marker cleanup is
        deliberately best-effort and can be finalized by the next load.
        """
        with cls.lock_run(state.run_id):
            cls._recover_pending_revision(state.run_id)
            cls._save_state_locked(state)

    @classmethod
    def _save_state_locked(cls, state: V2RunState) -> None:
        run_dir = cls.run_dir(state.run_id)
        cls._ensure_private_dir(run_dir)
        cls._harden_run_permissions(state.run_id)

        canonical_payload = cls._read_state_payload(state.run_id)
        if canonical_payload is not None and cls._is_sealed_public(canonical_payload):
            raise ImmutableRunError(
                "Sealed public baselines cannot be overwritten; fork an internal child run."
            )
        canonical_revision = (
            int(canonical_payload.get("state_revision", 0)) if canonical_payload is not None else None
        )
        canonical_audit = canonical_payload.get("audit_trail", []) if canonical_payload else []
        audit_prefix_size = cls._canonical_audit_prefix_size(state.run_id, canonical_audit)

        original_revision = state.state_revision
        original_updated_at = state.updated_at
        graph_had_state_revision = "state_revision" in state.graph
        original_graph_state_revision = state.graph.get("state_revision")

        state.touch()
        state.state_revision = original_revision + 1
        if state.graph:
            state.graph["state_revision"] = state.state_revision
        target_revision = state.state_revision
        confidential_writes = []
        original_storage_refs = []
        pending_payload = {
            "target_revision": target_revision,
            "canonical_revision": canonical_revision,
            "audit_jsonl_prefix_size": audit_prefix_size,
            "new_confidential_evidence_ids": [],
            "new_calculation_trace_ids": [],
        }

        try:
            confidential_writes, original_storage_refs = cls._prepare_confidential_answers(state)
            payload = cls._serialized_state(state)
            pending_payload["new_confidential_evidence_ids"] = [
                item[0] for item in confidential_writes if not item[3]
            ]
            if state.decision_analysis_trace_id and state.decision_analysis_trace is not None:
                trace_path = cls.calculation_trace_path(
                    state.run_id,
                    state.decision_analysis_trace_id,
                )
                if not trace_path.exists():
                    pending_payload["new_calculation_trace_ids"] = [
                        state.decision_analysis_trace_id
                    ]
            cls._atomic_write_json(cls._pending_revision_path(state.run_id), pending_payload)
            for _evidence_id, path, confidential_payload, already_exists in confidential_writes:
                if not already_exists:
                    cls._atomic_write_json(path, confidential_payload)
            cls._write_derived_artifacts(state)

            graph_history_dir = run_dir / "graph_revisions"
            cls._ensure_private_dir(graph_history_dir)
            graph_revision_path = graph_history_dir / f"revision_{target_revision:03d}.json"
            # A failed attempt may have left this target revision behind.  It is
            # uncommitted while canonical state is older, so always replace it.
            cls._atomic_write_json(graph_revision_path, state.graph)

            # Final and only commit point.  Nothing required may be written after
            # this replacement succeeds.
            cls._atomic_write_json(cls.state_path(state.run_id), payload)
        except Exception:
            # If an injected error happened after os.replace, the canonical file
            # still proves that the transaction committed.  Otherwise restore the
            # caller's in-memory revision so a retry does not skip a number.
            committed = cls._state_revision_on_disk(state.run_id) == target_revision
            if not committed:
                cls._cleanup_pending_confidential_files(state.run_id, pending_payload)
                cls._cleanup_pending_calculation_traces(state.run_id, pending_payload)
                for evidence, old_ref, old_run_id in original_storage_refs:
                    evidence.answer_storage_ref = old_ref
                    evidence.answer_storage_run_id = old_run_id
                state.state_revision = original_revision
                state.updated_at = original_updated_at
                if graph_had_state_revision:
                    state.graph["state_revision"] = original_graph_state_revision
                else:
                    state.graph.pop("state_revision", None)
                raise

        cls._remove_pending_marker_best_effort(state.run_id)

    @classmethod
    def _prepare_confidential_answers(cls, state: V2RunState):
        """Plan single-copy confidential writes and attach canonical references."""
        writes = []
        original_refs = []
        for evidence in state.internal_evidence:
            if not evidence.confidential:
                continue
            has_raw_answer = bool(
                evidence.answer
                and evidence.answer != cls.CONFIDENTIAL_ANSWER_MARKER
            )
            if evidence.answer_storage_ref:
                expected = cls._confidential_answer_path(state.run_id, evidence.evidence_id)
                if evidence.answer_storage_run_id not in {None, state.run_id}:
                    raise ConfidentialEvidenceError(
                        "Confidential evidence cannot reference an unrelated run."
                    )
                if evidence.answer_storage_ref != cls._confidential_relative_ref(evidence.evidence_id):
                    raise ConfidentialEvidenceError("Confidential evidence reference is invalid.")
                if expected.exists():
                    saved = cls._read_confidential_payload(expected, evidence.evidence_id)
                    if has_raw_answer and saved["answer"] != evidence.answer:
                        raise ConfidentialEvidenceError(
                            "Stored confidential evidence is immutable; submit superseding evidence instead."
                        )
                elif has_raw_answer:
                    cls._assert_confidential_storage_available()
                    writes.append(
                        (
                            evidence.evidence_id,
                            expected,
                            {
                                "evidence_id": evidence.evidence_id,
                                "answer": evidence.answer,
                                "created_at": evidence.created_at,
                            },
                            False,
                        )
                    )
                else:
                    raise ConfidentialEvidenceError(
                        "Referenced confidential evidence is missing."
                    )
                continue
            if not has_raw_answer:
                raise ConfidentialEvidenceError(
                    "Confidential evidence has neither an answer nor a storage reference."
                )
            cls._assert_confidential_storage_available()
            path = cls._confidential_answer_path(state.run_id, evidence.evidence_id)
            already_exists = path.exists()
            if already_exists:
                saved = cls._read_confidential_payload(path, evidence.evidence_id)
                if saved["answer"] != evidence.answer:
                    raise ConfidentialEvidenceError(
                        "Stored confidential evidence is immutable; submit superseding evidence instead."
                    )
            original_refs.append(
                (evidence, evidence.answer_storage_ref, evidence.answer_storage_run_id)
            )
            evidence.answer_storage_ref = cls._confidential_relative_ref(evidence.evidence_id)
            evidence.answer_storage_run_id = state.run_id
            writes.append(
                (
                    evidence.evidence_id,
                    path,
                    {
                        "evidence_id": evidence.evidence_id,
                        "answer": evidence.answer,
                        "created_at": evidence.created_at,
                    },
                    already_exists,
                )
            )
        return writes, original_refs

    @classmethod
    def _serialized_state(cls, state: V2RunState) -> Dict[str, Any]:
        payload: Dict[str, Any] = state.model_dump(mode="json")
        payload["internal_evidence"] = cls._serialized_internal_evidence(state)
        return payload

    @classmethod
    def _serialized_internal_evidence(cls, state: V2RunState) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for evidence in state.internal_evidence:
            row = evidence.model_dump(mode="json")
            if evidence.confidential:
                if not evidence.answer_storage_ref:
                    raise ConfidentialEvidenceError(
                        "Confidential evidence is missing its storage reference."
                    )
                row["answer"] = cls.CONFIDENTIAL_ANSWER_MARKER
            rows.append(row)
        return rows

    @classmethod
    def _assert_confidential_storage_available(cls) -> None:
        if Config.CONFIDENTIAL_STORAGE_MODE == "local_development":
            return
        raise ConfidentialStorageUnavailable(
            "Confidential storage is disabled until production key management is configured."
        )

    @classmethod
    def _confidential_relative_ref(cls, evidence_id: str) -> str:
        # The value is persisted as a portable reference, never as a host path.
        filename = safe_filename_path(Path("internal_evidence"), f"{evidence_id}.json").name
        return f"confidential/internal_evidence/{filename}"

    @classmethod
    def _confidential_answer_path(cls, run_id: str, evidence_id: str) -> Path:
        root = cls.run_dir(run_id) / "confidential" / "internal_evidence"
        cls._ensure_private_dir(root)
        try:
            return safe_filename_path(root, f"{evidence_id}.json", label="evidence ID")
        except UnsafePathError as exc:
            raise ConfidentialEvidenceError("Confidential evidence ID is invalid.") from exc

    @classmethod
    def _read_confidential_payload(cls, path: Path, evidence_id: str) -> Dict[str, Any]:
        try:
            with path.open("r", encoding="utf-8") as source:
                payload = json.load(source)
        except (OSError, json.JSONDecodeError) as exc:
            raise ConfidentialEvidenceError(
                "Confidential evidence could not be loaded."
            ) from exc
        if (
            not isinstance(payload, dict)
            or payload.get("evidence_id") != evidence_id
            or not isinstance(payload.get("answer"), str)
        ):
            raise ConfidentialEvidenceError("Confidential evidence payload is invalid.")
        return payload

    @classmethod
    def _hydrate_confidential_answers(cls, state: V2RunState) -> None:
        for evidence in state.internal_evidence:
            if not evidence.confidential or not evidence.answer_storage_ref:
                continue
            if evidence.answer_storage_run_id not in {None, state.run_id}:
                raise ConfidentialEvidenceError(
                    "Confidential evidence cannot reference an unrelated run."
                )
            expected_ref = cls._confidential_relative_ref(evidence.evidence_id)
            if evidence.answer_storage_ref != expected_ref:
                raise ConfidentialEvidenceError("Confidential evidence reference is invalid.")
            path = cls._confidential_answer_path(state.run_id, evidence.evidence_id)
            evidence.answer = cls._read_confidential_payload(path, evidence.evidence_id)["answer"]

    @classmethod
    def _cleanup_pending_confidential_files(
        cls,
        run_id: str,
        marker: Dict[str, Any],
    ) -> None:
        evidence_ids = marker.get("new_confidential_evidence_ids", [])
        if not isinstance(evidence_ids, list):
            return
        for evidence_id in evidence_ids:
            if not isinstance(evidence_id, str):
                continue
            try:
                cls._confidential_answer_path(run_id, evidence_id).unlink(missing_ok=True)
            except (OSError, ConfidentialEvidenceError):
                continue

    @classmethod
    def _cleanup_pending_calculation_traces(
        cls,
        run_id: str,
        marker: Dict[str, Any],
    ) -> None:
        trace_ids = marker.get("new_calculation_trace_ids", [])
        if not isinstance(trace_ids, list):
            return
        for trace_id in trace_ids:
            if not isinstance(trace_id, str):
                continue
            try:
                cls.calculation_trace_path(run_id, trace_id).unlink(missing_ok=True)
            except (OSError, FileNotFoundError):
                continue

    @staticmethod
    def _is_sealed_public(payload: Dict[str, Any]) -> bool:
        run_type = payload.get("run_type")
        if run_type is None:
            run_type = (
                "public"
                if payload.get("workflow_origin") == "core_mirofish_report"
                and not payload.get("internal_evidence")
                else "internal"
            )
        return run_type == "public" and bool(
            payload.get("sealed_at") or payload.get("status") == "sealed"
        )

    @classmethod
    def _write_derived_artifacts(cls, state: V2RunState) -> None:
        cls._write_artifact(state.run_id, "graph.json", state.graph)
        cls._write_artifact(
            state.run_id,
            "assumptions.json",
            [item.model_dump(mode="json") for item in state.assumptions],
        )
        cls._write_artifact(
            state.run_id,
            "contradictions.json",
            [item.model_dump(mode="json") for item in state.contradictions],
        )
        cls._write_artifact(
            state.run_id,
            "hypotheses.json",
            [item.model_dump(mode="json") for item in state.hypotheses],
        )
        cls._write_artifact(
            state.run_id,
            "internal_questions.json",
            [item.model_dump(mode="json") for item in state.internal_questions],
        )
        cls._write_artifact(
            state.run_id,
            "internal_evidence.json",
            cls._serialized_internal_evidence(state),
        )
        cls._write_artifact(
            state.run_id,
            "decision_impacts.json",
            [item.model_dump(mode="json") for item in state.decision_impacts],
        )
        cls._write_artifact(
            state.run_id,
            "execution_plan.json",
            state.execution_plan.model_dump(mode="json") if state.execution_plan else {},
        )
        cls._write_artifact(
            state.run_id,
            "stop_evaluation.json",
            state.stop_evaluation.model_dump(mode="json") if state.stop_evaluation else {},
        )
        audit_rows = [item.model_dump(mode="json") for item in state.audit_trail]
        cls._write_artifact(state.run_id, "audit_trail.json", audit_rows)
        cls._append_jsonl(state.run_id, "audit_trail.jsonl", audit_rows)
        cls._write_artifact(
            state.run_id,
            "token_usage.json",
            state.token_usage.model_dump(mode="json"),
        )
        cls._write_artifact(
            state.run_id,
            "core_lineage.json",
            state.core_lineage.model_dump(mode="json") if state.core_lineage else {},
        )
        cls._write_artifact(
            state.run_id,
            "research_job.json",
            state.research_job.model_dump(mode="json") if state.research_job else {},
        )
        cls._write_artifact(
            state.run_id,
            "targeted_reevaluations.json",
            [item.model_dump(mode="json") for item in state.targeted_reevaluations],
        )
        cls._write_artifact(
            state.run_id,
            "decision_model_proposal.json",
            state.decision_model_proposal or {},
        )
        cls._write_artifact(
            state.run_id,
            "decision_model.json",
            state.decision_model or {},
        )
        cls._write_artifact(
            state.run_id,
            "decision_analysis_result.json",
            state.decision_analysis_result or {},
        )
        cls._write_artifact(
            state.run_id,
            "decision_analysis_options.json",
            state.decision_analysis_options,
        )
        cls._write_artifact(
            state.run_id,
            "decision_analysis_audit.json",
            state.decision_analysis_audit or {},
        )
        cls._write_artifact(
            state.run_id,
            "evidence_update_proposals.json",
            state.evidence_update_proposals,
        )
        if state.decision_analysis_trace_id and state.decision_analysis_trace is not None:
            cls._atomic_write_json(
                cls.calculation_trace_path(
                    state.run_id,
                    state.decision_analysis_trace_id,
                ),
                state.decision_analysis_trace,
            )
        if state.report:
            cls._atomic_write_text(cls.report_path(state.run_id), state.report.markdown)
        else:
            cls._remove_file_if_present(cls.report_path(state.run_id))

    @classmethod
    @contextmanager
    def lock_run(cls, run_id: str, *, require_existing: bool = False):
        """Serialize local read-modify-write transactions for one decision case."""
        run_dir = cls.run_dir(run_id)
        if require_existing and not cls.state_path(run_id).is_file():
            raise FileNotFoundError(f"v2 run not found: {run_id}")
        cls._ensure_private_dir(run_dir)
        lock_path = run_dir / ".state.lock"
        lock_key = str(lock_path)
        with cls._LOCKS_GUARD:
            process_lock = cls._PROCESS_LOCKS.setdefault(lock_key, threading.RLock())
        with process_lock:
            depths = getattr(cls._LOCK_DEPTHS, "values", None)
            if depths is None:
                depths = {}
                cls._LOCK_DEPTHS.values = depths
            if depths.get(lock_key, 0):
                depths[lock_key] += 1
                try:
                    yield
                finally:
                    depths[lock_key] -= 1
                return

            lock_fd = os.open(lock_path, os.O_RDWR | os.O_APPEND | os.O_CREAT, 0o600)
            with os.fdopen(lock_fd, "a+", encoding="utf-8") as lock_file:
                if fcntl is not None:
                    fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
                depths[lock_key] = 1
                try:
                    yield
                finally:
                    depths.pop(lock_key, None)
                    if fcntl is not None:
                        fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)

    @classmethod
    def load_state(cls, run_id: str) -> V2RunState:
        path = cls.state_path(run_id)
        if not path.exists():
            raise FileNotFoundError(f"v2 run not found: {run_id}")
        with cls.lock_run(run_id):
            # Recheck after waiting for a writer: a provisional/failed initial
            # transaction may have been cleaned up while this reader blocked.
            if not path.exists():
                raise FileNotFoundError(f"v2 run not found: {run_id}")
            cls._recover_pending_revision(run_id)
            cls._harden_run_permissions(run_id)
            payload = cls._read_state_payload(run_id)
            if payload is None:  # pragma: no cover - guarded by the checks above
                raise FileNotFoundError(f"v2 run not found: {run_id}")
            state = V2RunState.model_validate(payload)
            cls._hydrate_confidential_answers(state)
            return state

    @classmethod
    def _recover_pending_revision(cls, run_id: str) -> None:
        marker_path = cls._pending_revision_path(run_id)
        if not marker_path.exists():
            return

        with marker_path.open("r", encoding="utf-8") as marker_file:
            marker = json.load(marker_file)
        target_revision = int(marker["target_revision"])
        canonical_payload = cls._read_state_payload(run_id)
        canonical_revision = (
            int(canonical_payload.get("state_revision", 0)) if canonical_payload is not None else None
        )

        if canonical_revision == target_revision:
            # All derived writes preceded the state commit, so this is only a
            # marker-cleanup retry.  Cleanup remains optional for readability.
            cls._remove_pending_marker_best_effort(run_id)
            return

        # The target never committed.  Rebuild every public derivative from the
        # canonical old state before exposing it, and remove snapshots newer than
        # that state so a retry cannot inherit a poisoned graph revision.
        audit_prefix_size = int(marker.get("audit_jsonl_prefix_size", 0))
        cls._cleanup_pending_confidential_files(run_id, marker)
        cls._cleanup_pending_calculation_traces(run_id, marker)
        if canonical_payload is None:
            cls._remove_uncommitted_derivatives(run_id)
        else:
            cls._restore_canonical_derivatives(run_id, canonical_payload, audit_prefix_size)
        cls._remove_graph_snapshots_after(run_id, canonical_revision or 0)
        marker_path.unlink()

    @classmethod
    def _restore_canonical_derivatives(
        cls,
        run_id: str,
        payload: Dict[str, Any],
        audit_prefix_size: int,
    ) -> None:
        state = V2RunState.model_validate(payload)
        confidential_writes, _original_refs = cls._prepare_confidential_answers(state)
        for _evidence_id, path, confidential_payload, already_exists in confidential_writes:
            if not already_exists:
                cls._atomic_write_json(path, confidential_payload)
        audit_path = cls.artifact_path(run_id, "audit_trail.jsonl")
        cls._truncate_file(audit_path, audit_prefix_size)

        # JSONL must represent the canonical audit list, but its already-committed
        # prefix is retained byte-for-byte and only missing canonical rows append.
        cls._write_derived_artifacts(state)

    @classmethod
    def _remove_uncommitted_derivatives(cls, run_id: str) -> None:
        for filename in (*cls.DERIVED_JSON_ARTIFACTS, "audit_trail.jsonl"):
            cls._remove_file_if_present(cls.artifact_path(run_id, filename))
        cls._remove_file_if_present(cls.report_path(run_id))

    @classmethod
    def _remove_graph_snapshots_after(cls, run_id: str, canonical_revision: int) -> None:
        graph_history_dir = cls.run_dir(run_id) / "graph_revisions"
        if not graph_history_dir.exists():
            return
        for path in graph_history_dir.glob("revision_*.json"):
            try:
                revision = int(path.stem.rsplit("_", 1)[1])
            except (IndexError, ValueError):
                continue
            if revision > canonical_revision:
                path.unlink()

    @classmethod
    def _canonical_audit_prefix_size(cls, run_id: str, rows: Any) -> int:
        path = cls.artifact_path(run_id, "audit_trail.jsonl")
        if not path.exists() or not rows:
            return 0
        expected_ids = [row.get("event_id") for row in rows]
        raw = path.read_bytes()
        valid_end = 0
        matched = 0
        for line in raw.splitlines(keepends=True):
            if matched >= len(expected_ids):
                break
            candidate = line.rstrip(b"\r\n")
            try:
                decoded = json.loads(candidate.decode("utf-8"))
                event_id = decoded.get("event_id")
            except (UnicodeDecodeError, json.JSONDecodeError, AttributeError):
                break
            if event_id != expected_ids[matched]:
                break
            valid_end += len(line)
            matched += 1
        return valid_end

    @classmethod
    def _pending_revision_path(cls, run_id: str) -> Path:
        return cls.run_dir(run_id) / cls.PENDING_REVISION_FILENAME

    @classmethod
    def _read_state_payload(cls, run_id: str) -> Dict[str, Any] | None:
        path = cls.state_path(run_id)
        if not path.exists():
            return None
        with path.open("r", encoding="utf-8") as state_file:
            return json.load(state_file)

    @classmethod
    def _state_revision_on_disk(cls, run_id: str) -> int | None:
        try:
            payload = cls._read_state_payload(run_id)
            return int(payload.get("state_revision", 0)) if payload is not None else None
        except (OSError, ValueError, TypeError, json.JSONDecodeError):
            return None

    @classmethod
    def _remove_pending_marker_best_effort(cls, run_id: str) -> None:
        try:
            cls._pending_revision_path(run_id).unlink(missing_ok=True)
        except OSError:
            # The state commit is authoritative; a later load recognizes the
            # committed target and retries this optional cleanup.
            pass

    @classmethod
    def _remove_file_if_present(cls, path: Path) -> None:
        path.unlink(missing_ok=True)

    @classmethod
    def _truncate_file(cls, path: Path, size: int) -> None:
        if not path.exists():
            return
        with path.open("r+b") as output:
            output.truncate(size)
            output.flush()
            os.fsync(output.fileno())
        cls._harden_file(path)

    @classmethod
    def safe_filename(cls, filename: str) -> str:
        base = os.path.basename(filename or "document.txt")
        safe = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in base)
        return safe or "document.txt"

    @classmethod
    def _write_artifact(cls, run_id: str, filename: str, payload: Any) -> None:
        cls._atomic_write_json(cls.artifact_path(run_id, filename), payload)

    @classmethod
    def _append_jsonl(cls, run_id: str, filename: str, rows: Any) -> None:
        path = cls.artifact_path(run_id, filename)
        existing_ids = set()
        needs_separator = False
        if path.exists():
            raw = path.read_bytes()
            valid_end = 0
            for line in raw.splitlines(keepends=True):
                candidate = line.rstrip(b"\r\n")
                try:
                    payload = json.loads(candidate.decode("utf-8"))
                    event_id = payload.get("event_id")
                except (UnicodeDecodeError, json.JSONDecodeError, AttributeError):
                    break
                valid_end += len(line)
                if event_id:
                    existing_ids.add(event_id)
            if valid_end < len(raw):
                with path.open("r+b") as existing:
                    existing.truncate(valid_end)
                    existing.flush()
                    os.fsync(existing.fileno())
                raw = raw[:valid_end]
            needs_separator = bool(raw and not raw.endswith((b"\n", b"\r")))
        missing = [row for row in rows if row.get("event_id") not in existing_ids]
        if not missing:
            return
        output_fd = os.open(path, os.O_WRONLY | os.O_APPEND | os.O_CREAT, 0o600)
        with os.fdopen(output_fd, "a", encoding="utf-8") as output:
            if needs_separator:
                output.write("\n")
            for row in missing:
                output.write(json.dumps(row, ensure_ascii=False) + "\n")
            output.flush()
            os.fsync(output.fileno())

    @classmethod
    def _atomic_write_json(cls, path: Path, payload: Any) -> None:
        cls._atomic_write_text(path, json.dumps(payload, ensure_ascii=False, indent=2))

    @classmethod
    def _atomic_write_text(cls, path: Path, text: str) -> None:
        cls._ensure_private_dir(path.parent)
        temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
        try:
            temporary_fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(temporary_fd, "w", encoding="utf-8") as output:
                output.write(text)
                output.flush()
                os.fsync(output.fileno())
            os.replace(temporary, path)
            cls._harden_file(path)
        except Exception:
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass
            raise

    @staticmethod
    def _harden_file(path: Path) -> None:
        try:
            path.chmod(0o600)
        except OSError:  # pragma: no cover - permission modes vary on Windows
            pass

    @classmethod
    def _ensure_private_dir(cls, path: Path) -> None:
        path.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            path.chmod(0o700)
        except OSError:  # pragma: no cover - permission modes vary on Windows
            pass

    @classmethod
    def _harden_run_permissions(cls, run_id: str) -> None:
        """Migrate an existing case to owner-only filesystem permissions."""
        run_dir = cls.run_dir(run_id)
        if not run_dir.exists():
            return
        cls._ensure_private_dir(run_dir)
        for child in run_dir.rglob("*"):
            if child.is_symlink():
                continue
            if child.is_dir():
                cls._ensure_private_dir(child)
            elif child.is_file():
                cls._harden_file(child)
